export interface ComponentCloseupCatalogEntry {
  covers: readonly string[];
  probes?: readonly string[];
  title: string;
}

export const requiredVisualPrimitiveExports = [
  "AgentChat",
  "AgentShell",
  "AgentThreadView",
  "AgentThreadSurface",
  "AgentThreadHeader",
  "AgentThreadTimeline",
  "AgentMessageList",
  "AgentTranscript",
  "AgentTurn",
  "AgentApprovalQueue",
  "AgentComposer",
  "AgentComposerInput",
  "AgentComposerToolbar",
  "AgentComposerSubmitButton",
  "AgentAttachmentChips",
  "AgentFirstRun",
  "AgentStartComposer",
  "AgentStarterCwd",
  "AgentRunControls",
  "ComposerRunControls",
  "AgentThreadSidebar",
  "ThreadList",
  "AgentStatusBar",
  "AgentStatusSummary",
  "AgentStatusDetails",
  "AgentCriticalNoticeList",
  "AgentDiagnosticsPanel",
  "AgentUsagePanel",
  "AgentUsageSummary",
  "AgentRateLimitBar",
  "AgentTokenUsageBar",
  "AgentContextUsageIndicator",
  "AgentSkillsPanel",
  "AgentAppsPanel",
  "AgentLocaleSelect",
  "AgentThemeToggle",
  "AgentDiffViewer",
  "AgentDiffItem",
  "AgentContentBlockView",
  "AgentCommandItem",
  "AgentCommandOutputItem",
  "AgentFileChangeItem",
  "AgentReasoningItem",
  "AgentToolCallItem",
  "AgentMessageItem",
] as const;

export const intentionalNonVisualPrimitiveExports = [
  "AgentAttachmentChip",
  "AgentAttachmentChipKind",
  "AgentAttachmentChipsProps",
  "AgentComposerInputProps",
  "AgentComposerIntegration",
  "AgentComposerIntegrationAttachment",
  "AgentComposerIntegrationResolver",
  "AgentComposerProps",
  "AgentComposerSubmitButtonProps",
  "AgentComposerToolbarProps",
  "AgentFileResourceRequest",
  "AgentI18nDictionary",
  "AgentI18nKey",
  "AgentI18nMessages",
  "AgentI18nProvider",
  "AgentI18nProviderProps",
  "AgentI18nValue",
  "AgentImageInput",
  "AgentLocalAttachmentKind",
  "AgentLocalAttachmentResolver",
  "AgentLocalImageInput",
  "AgentLocalMediaResourceRequest",
  "AgentLocalMediaUrlResolver",
  "AgentLocale",
  "AgentLocaleSelectProps",
  "AgentMentionInput",
  "AgentResolvedLocalAttachment",
  "AgentResolvedResource",
  "AgentResolvedResourceBase",
  "AgentResolvedUrlResource",
  "AgentResourceKind",
  "AgentResourceRequest",
  "AgentResourceResolution",
  "AgentResourceResolver",
  "AgentRunControlsProps",
  "AgentShellProps",
  "AgentSkillInput",
  "AgentStartComposerProps",
  "AgentStatusBarProps",
  "AgentTextInput",
  "AgentThreadHeaderEnd",
  "AgentThreadHeaderEndContext",
  "AgentThreadHeaderProps",
  "AgentThreadViewProps",
  "AgentTheme",
  "AgentThemeToggleProps",
  "AgentUnavailableResource",
  "AgentUnknownUserInput",
  "AgentUsageProps",
  "AgentUserInput",
  "AgentWorkingDirectoryResolver",
  "TranscriptApprovalAnchors",
  "UsageWindow",
  "agentI18nDictionaries",
  "agentLocales",
  "agentResourceDisplayName",
  "agentResourceUrl",
  "formatThreadStatus",
  "interpolate",
  "interpolationVariables",
  "isUserFacingPath",
  "normalizeAgentLocale",
  "normalizeUsageWindows",
  "threadSubtitle",
  "useAgentI18n",
] as const;

export const componentCloseupCatalog = [
  {
    title: "Composer · normal",
    covers: ["AgentComposer", "AgentComposerSubmitButton", "ComposerRunControls"],
    probes: [".aui-composer-input", ".aui-composer-toolbar", 'button[aria-label="Send"]'],
  },
  { title: "Composer · focused", covers: ["AgentComposer"] },
  { title: "Composer · approval pending", covers: ["AgentComposer"] },
  {
    title: "Composer · mobile",
    covers: ["AgentComposer"],
    probes: [".aui-composer-input", 'button[aria-label="Send"]'],
  },
  {
    title: "Composer parts",
    covers: ["AgentComposer", "AgentComposerInput", "AgentComposerToolbar"],
    probes: [".aui-composer", ".aui-composer-input", ".aui-composer-toolbar"],
  },
  { title: "Composer · pasted image", covers: ["AgentComposer", "AgentAttachmentChips"] },
  { title: "Composer · multiple attachments", covers: ["AgentComposer", "AgentAttachmentChips"] },
  {
    title: "Composer submit button",
    covers: ["AgentComposerSubmitButton"],
    probes: ['button[aria-label="Send"]'],
  },
  {
    title: "Attachment chips",
    covers: ["AgentAttachmentChips"],
    probes: [".aui-composer-chips", ".aui-composer-chip"],
  },
  { title: "Composer run controls · compact", covers: ["AgentComposer", "ComposerRunControls"] },
  {
    title: "Run policy and model controls",
    covers: ["AgentRunControls"],
    probes: [".aui-run-controls"],
  },
  { title: "Thread-start controls", covers: ["AgentRunControls", "AgentStarterCwd"] },
  {
    title: "Mobile chat shell",
    covers: ["AgentShell", "AgentComposer", "AgentComposerSubmitButton"],
    probes: [".aui-shell", ".aui-composer-input", 'button[aria-label="Send"]'],
  },
  { title: "Empty state · mobile", covers: ["AgentFirstRun"] },
  { title: "Start composer", covers: ["AgentStartComposer"] },
  { title: "Thread surface + header", covers: ["AgentThreadSurface", "AgentThreadHeader"] },
  { title: "Thread view", covers: ["AgentThreadView"] },
  { title: "Thread timeline", covers: ["AgentThreadTimeline", "AgentMessageList", "AgentTranscript", "AgentTurn"] },
  {
    title: "Sidebar search",
    covers: ["AgentThreadSidebar"],
    probes: [".aui-sidebar"],
  },
  {
    title: "Thread list",
    covers: ["ThreadList"],
    probes: [".aui-thread-list", ".aui-thread-list-item"],
  },
  { title: "Sidebar drawer search/select", covers: ["AgentChat", "AgentThreadSidebar", "ThreadList"] },
  { title: "Approval queue · 3 pending", covers: ["AgentApprovalQueue"] },
  { title: "Approval · command", covers: ["AgentApprovalQueue"] },
  { title: "Approval · user input", covers: ["AgentApprovalQueue"] },
  {
    title: "Command block",
    covers: ["AgentContentBlockView", "AgentCommandItem", "AgentCommandOutputItem"],
    probes: [".aui-command-card"],
  },
  { title: "Custom command block", covers: ["AgentMessageList", "AgentCommandItem", "AgentApprovalQueue"] },
  { title: "Transcript content blocks", covers: ["AgentContentBlockView", "AgentReasoningItem", "AgentToolCallItem", "AgentMessageItem"] },
  {
    title: "Diff / file change",
    covers: ["AgentDiffViewer", "AgentDiffItem", "AgentFileChangeItem"],
    probes: [".aui-diff", ".aui-file-change-card"],
  },
  { title: "Local media fallback card", covers: ["AgentMessageList", "AgentContentBlockView"] },
  { title: "Optimistic pending message", covers: ["AgentMessageList"] },
  { title: "Status bar · standalone", covers: ["AgentStatusBar", "AgentStatusSummary"] },
  { title: "Status banners · severity stack", covers: ["AgentStatusSummary", "AgentStatusDetails", "AgentCriticalNoticeList"] },
  {
    title: "Diagnostics panel",
    covers: ["AgentDiagnosticsPanel"],
    probes: [".aui-diagnostics"],
  },
  { title: "Usage / status chips", covers: ["AgentUsageSummary", "AgentRateLimitBar", "AgentTokenUsageBar"] },
  { title: "Context usage indicator", covers: ["AgentContextUsageIndicator"] },
  { title: "Usage panel", covers: ["AgentUsagePanel"] },
  {
    title: "Apps and skills panels",
    covers: ["AgentAppsPanel", "AgentSkillsPanel"],
    probes: [".aui-apps-panel", ".aui-skills-panel"],
  },
  {
    title: "Locale and theme controls",
    covers: ["AgentLocaleSelect", "AgentThemeToggle"],
    probes: [".aui-locale-trigger", ".aui-theme-toggle"],
  },
  { title: "Button system", covers: [] },
] as const satisfies readonly ComponentCloseupCatalogEntry[];

export function closeupCoverageForTitle(title: string): readonly string[] {
  return componentCloseupCatalog.find((entry) => entry.title === title)?.covers ?? [];
}
