import { C as CodexStableMethodParams, U as UserInput } from './method-params-s6VeRfnU.js';
export { a as CodexStableMethod } from './method-params-s6VeRfnU.js';
import './InitializeParams-CDX1c2T9.js';

type AppsListParams = CodexStableMethodParams<"app/list">;
type CancelLoginAccountParams = CodexStableMethodParams<"account/login/cancel">;
type GetAccountParams = CodexStableMethodParams<"account/read">;
type HooksListParams = CodexStableMethodParams<"hooks/list">;
type LoginAccountParams = CodexStableMethodParams<"account/login/start">;
type ModelListParams = CodexStableMethodParams<"model/list">;
type SkillsConfigWriteParams = CodexStableMethodParams<"skills/config/write">;
type SkillsListParams = CodexStableMethodParams<"skills/list">;
type ThreadArchiveParams = CodexStableMethodParams<"thread/archive">;
type ThreadCompactStartParams = CodexStableMethodParams<"thread/compact/start">;
type ThreadForkParams = CodexStableMethodParams<"thread/fork">;
type ThreadInjectItemsParams = CodexStableMethodParams<"thread/inject_items">;
type ThreadListParams = CodexStableMethodParams<"thread/list">;
type ThreadLoadedListParams = CodexStableMethodParams<"thread/loaded/list">;
type ThreadMetadataUpdateParams = CodexStableMethodParams<"thread/metadata/update">;
type ThreadReadParams = CodexStableMethodParams<"thread/read">;
type ThreadResumeParams = CodexStableMethodParams<"thread/resume">;
type ThreadRollbackParams = CodexStableMethodParams<"thread/rollback">;
type ThreadSetNameParams = CodexStableMethodParams<"thread/name/set">;
type ThreadStartParams = CodexStableMethodParams<"thread/start">;
type ThreadUnarchiveParams = CodexStableMethodParams<"thread/unarchive">;
type ThreadUnsubscribeParams = CodexStableMethodParams<"thread/unsubscribe">;
type TurnInterruptParams = CodexStableMethodParams<"turn/interrupt">;
type TurnStartParams = CodexStableMethodParams<"turn/start">;
type TurnSteerParams = CodexStableMethodParams<"turn/steer">;
type CodexUserInput = UserInput;
interface AgentBrowserVerificationInputOptions {
    prompt: string;
    skillPath: string;
    skillName?: string;
}
declare const disabledProductMethods: readonly ["thread/turns/items/list"];
declare function accountReadParams(refreshToken?: boolean): GetAccountParams;
declare function deviceCodeLoginParams(): LoginAccountParams;
declare function chatgptLoginParams(codexStreamlinedLogin?: boolean): LoginAccountParams;
declare function apiKeyLoginParams(apiKey: string): LoginAccountParams;
declare function authTokensLoginParams(params: {
    accessToken: string;
    chatgptAccountId: string;
    chatgptPlanType?: string | null;
}): LoginAccountParams;
declare function cancelLoginParams(loginId: string): CancelLoginAccountParams;
declare function modelListParams(params?: ModelListParams): ModelListParams;
declare function threadListParams(params?: ThreadListParams): ThreadListParams;
declare function threadLoadedListParams(params?: ThreadLoadedListParams): ThreadLoadedListParams;
declare function threadReadParams(threadId: string, includeTurns?: boolean): ThreadReadParams;
declare function threadResumeParams(threadId: string, params?: Omit<ThreadResumeParams, "threadId">): ThreadResumeParams;
declare function threadStartParams(options?: ThreadStartParams): ThreadStartParams;
declare function threadForkParams(threadId: string, params?: Omit<ThreadForkParams, "threadId">): ThreadForkParams;
declare function threadArchiveParams(threadId: string): ThreadArchiveParams;
declare function threadUnarchiveParams(threadId: string): ThreadUnarchiveParams;
declare function threadSetNameParams(threadId: string, name: string): ThreadSetNameParams;
declare function threadMetadataUpdateParams(threadId: string, params?: Omit<ThreadMetadataUpdateParams, "threadId">): ThreadMetadataUpdateParams;
declare function threadCompactStartParams(threadId: string): ThreadCompactStartParams;
declare function threadRollbackParams(threadId: string, numTurns: number): ThreadRollbackParams;
declare function threadInjectItemsParams(threadId: string, items: ThreadInjectItemsParams["items"]): ThreadInjectItemsParams;
declare function threadUnsubscribeParams(threadId: string): ThreadUnsubscribeParams;
declare function turnStartParams(options: {
    input: string | UserInput[];
    threadId: string;
} & Omit<TurnStartParams, "input" | "threadId">): TurnStartParams;
declare function turnSteerParams(options: {
    expectedTurnId: string;
    input: string | UserInput[];
    threadId: string;
}): TurnSteerParams;
declare function skillInput(name: string, path: string): UserInput;
declare function mentionInput(name: string, path: string): UserInput;
declare function localImageInput(path: string): UserInput;
declare function imageInput(url: string): UserInput;
declare function textInput(text: string): UserInput;
declare function agentBrowserSkillInput(path: string): UserInput;
declare function agentBrowserVerificationInput({ prompt, skillName, skillPath, }: AgentBrowserVerificationInputOptions): UserInput[];
declare function turnInterruptParams(threadId: string, turnId: string): TurnInterruptParams;
declare function skillsListParams(params?: SkillsListParams): SkillsListParams;
declare function skillsConfigWriteParams(params: SkillsConfigWriteParams): SkillsConfigWriteParams;
declare function hooksListParams(params?: HooksListParams): HooksListParams;
declare function appsListParams(params?: AppsListParams): AppsListParams;

export { type AgentBrowserVerificationInputOptions, type AppsListParams, type CancelLoginAccountParams, CodexStableMethodParams, type CodexUserInput, type GetAccountParams, type HooksListParams, type LoginAccountParams, type ModelListParams, type SkillsConfigWriteParams, type SkillsListParams, type ThreadArchiveParams, type ThreadCompactStartParams, type ThreadForkParams, type ThreadInjectItemsParams, type ThreadListParams, type ThreadLoadedListParams, type ThreadMetadataUpdateParams, type ThreadReadParams, type ThreadResumeParams, type ThreadRollbackParams, type ThreadSetNameParams, type ThreadStartParams, type ThreadUnarchiveParams, type ThreadUnsubscribeParams, type TurnInterruptParams, type TurnStartParams, type TurnSteerParams, UserInput, accountReadParams, agentBrowserSkillInput, agentBrowserVerificationInput, apiKeyLoginParams, appsListParams, authTokensLoginParams, cancelLoginParams, chatgptLoginParams, deviceCodeLoginParams, disabledProductMethods, hooksListParams, imageInput, localImageInput, mentionInput, modelListParams, skillInput, skillsConfigWriteParams, skillsListParams, textInput, threadArchiveParams, threadCompactStartParams, threadForkParams, threadInjectItemsParams, threadListParams, threadLoadedListParams, threadMetadataUpdateParams, threadReadParams, threadResumeParams, threadRollbackParams, threadSetNameParams, threadStartParams, threadUnarchiveParams, threadUnsubscribeParams, turnInterruptParams, turnStartParams, turnSteerParams };
