import type { StableNotificationMethod } from "../protocol";

export type StableNotificationCoverage = "mapped" | "raw" | "ignored" | "unsupported";

export const stableNotificationCoverage: Record<
  StableNotificationMethod,
  StableNotificationCoverage
> = {
  "account/login/completed": "mapped",
  "account/rateLimits/updated": "mapped",
  "account/updated": "mapped",
  "app/list/updated": "mapped",
  "command/exec/outputDelta": "mapped",
  configWarning: "mapped",
  deprecationNotice: "mapped",
  error: "mapped",
  "externalAgentConfig/import/completed": "raw",
  "fs/changed": "raw",
  "fuzzyFileSearch/sessionCompleted": "raw",
  "fuzzyFileSearch/sessionUpdated": "raw",
  guardianWarning: "raw",
  "hook/completed": "raw",
  "hook/started": "raw",
  "item/agentMessage/delta": "mapped",
  "item/autoApprovalReview/completed": "raw",
  "item/autoApprovalReview/started": "raw",
  "item/commandExecution/outputDelta": "mapped",
  "item/commandExecution/terminalInteraction": "raw",
  "item/completed": "mapped",
  "item/fileChange/outputDelta": "mapped",
  "item/fileChange/patchUpdated": "mapped",
  "item/mcpToolCall/progress": "raw",
  "item/plan/delta": "raw",
  "item/reasoning/summaryPartAdded": "raw",
  "item/reasoning/summaryTextDelta": "mapped",
  "item/reasoning/textDelta": "raw",
  "item/started": "mapped",
  "mcpServer/oauthLogin/completed": "mapped",
  "mcpServer/startupStatus/updated": "mapped",
  "model/rerouted": "mapped",
  "model/verification": "raw",
  "process/exited": "raw",
  "process/outputDelta": "raw",
  "rawResponseItem/completed": "raw",
  "remoteControl/status/changed": "raw",
  "serverRequest/resolved": "mapped",
  "skills/changed": "mapped",
  "thread/archived": "mapped",
  "thread/closed": "mapped",
  "thread/compacted": "raw",
  "thread/deleted": "raw",
  "thread/goal/cleared": "raw",
  "thread/goal/updated": "raw",
  "thread/name/updated": "mapped",
  "thread/realtime/closed": "raw",
  "thread/realtime/error": "raw",
  "thread/realtime/itemAdded": "raw",
  "thread/realtime/outputAudio/delta": "raw",
  "thread/realtime/sdp": "raw",
  "thread/realtime/started": "raw",
  "thread/realtime/transcript/delta": "raw",
  "thread/realtime/transcript/done": "raw",
  "thread/settings/updated": "raw",
  "thread/started": "mapped",
  "thread/status/changed": "mapped",
  "thread/tokenUsage/updated": "mapped",
  "thread/unarchived": "mapped",
  "turn/completed": "mapped",
  "turn/diff/updated": "mapped",
  "turn/moderationMetadata": "raw",
  "turn/plan/updated": "mapped",
  "turn/started": "mapped",
  warning: "mapped",
  "windows/worldWritableWarning": "raw",
  "windowsSandbox/setupCompleted": "raw",
};
